### ISSUE TITLE
Incorrect Refinement level

### ISSUE THREAD

**Issue by TheSast** [seriaati/enka-to-go#1]
The tool will report a refinement level 1 lower compared to what is actually equipped on the character or shown on [enka](https://enka.network).

![image](https://github.com/seriaati/enka-to-go/assets/27977196/553ddc8a-1616-4c61-9a53-61eaac882406)
![image](https://github.com/seriaati/enka-to-go/assets/27977196/8a0b0b96-86c0-401a-9f13-c7f251c9367c)

**Comment by seriaati** [comment]
Should be fixed, can you confirm?
